### ISSUE TITLE
Recommended way to add to a monorepo

### ISSUE THREAD

**Issue by thenbe** [total-typescript/ts-reset#24] opened 2023-02-21 01:37 UTC
Assuming you have a monorepo setup like [this](https://turbo.build/repo/docs/handbook/linting/typescript#sharing-tsconfigjson), is there a way to add it to the `packages/tsconfig` and have the types propagate throughout your monorepo? Or does this need to be installed and imported in each package?

I tried adding it to the types array in `base.json`:
```json
// packages/tsconfig/base.json
{
  "compilerOptions": {
    "types": ["@total-typescript/ts-reset"],
  }
}
```

But got an error in the other apps whose `tsconfigs` extend from `base.json`:

```
error TS2688: Cannot find type definition file for '@total-typescript/ts-reset'.
  The file is in the program because:
    Entry point of type library '@total-typescript/ts-reset' specified in compilerOptions
```

**Comment by tom-sherman** [comment] 2023-02-21 08:14
Did you add the reset as a dependency of the base config package?

**Comment by thenbe** [comment] 2023-02-21 14:53
> Did you add the reset as a dependency of the base config package?

Yes. Tried adding it both as a dependency + dev dependency. Both resulted in the same error message.

**Comment by John-Dennehy** [comment] 2023-02-21 17:10
I don't think it has been designed to work with tsconfig.  

I confirm it works in my turbo monorepo, as a root devDependancy, with each 'app' I want using it having a single import statement (such as _app.tsx in nextjs apps).

**Comment by tom-sherman** [comment] 2023-02-21 17:44
I'm confused about why it wouldn't work though, isn't it the same as the global types provided by eg. `@types/node`?

**Comment by essenmitsosse** [comment] 2023-02-22 11:15
I think it is implemented as types that you need to manually import in the run-time code — so no it works differently then the DefinitelyTyped types.

**Comment by mattpocock** [comment] 2023-02-22 12:27
Since the intention of this thread is to get it working in `tsconfig.json`, I'll close this as a duplicate of #30

**Closed by mattpocock** 2023-02-22 12:27 UTC
