### ISSUE TITLE
BUG: Importing "filter-boolean" only does not seem to work

### ISSUE THREAD

**Issue by Jeremias-Nater** [total-typescript/ts-reset#73] opened 2023-02-24 12:22 UTC
When importing the whole ts-reset like following, i get the correct type narrowing from, filter-boolean:
```
import '@total-typescript/ts-reset/';
```
![Bildschirmfoto 2023-02-24 um 13 21 43](https://user-images.githubusercontent.com/8191311/221177905-ccc59392-9c23-4af8-ac03-4b2c14a65a35.png)

When using only filter-boolean it does not work:

```
import '@total-typescript/ts-reset/filter-boolean';
```

![Bildschirmfoto 2023-02-24 um 13 22 24](https://user-images.githubusercontent.com/8191311/221177992-049c9aed-75f1-4750-8612-48119a9c543b.png)

**Comment by m10rten** [comment] 2023-02-24 13:06
Have you tried reloading the window?

**Comment by neiker** [comment] 2023-02-24 13:56
I'm having exactly same issue with `@total-typescript/ts-reset/array-includes`

**Comment by m10rten** [comment] 2023-02-24 14:37
> I'm having exactly same issue with `@total-typescript/ts-reset/array-includes`.
> 
> Importing `@total-typescript/ts-reset` works, importing `@total-typescript/ts-reset/array-includes` doesn't

So it is not exclusive for filter-boolean.

Could you try it for each of the files?
And maybe list what files are working when imported solo.

**Comment by fahadsohail482** [comment] 2023-02-24 14:48
@m10rten All are working through dist folder imports 
`import "@total-typescript/ts-reset/dist/filter-boolean";`
@mattpocock can you look at this ?

**Comment by m10rten** [comment] 2023-02-24 14:55
As if all are only available through /dist, when all should redirect to /dist

**Comment by mattpocock** [comment] 2023-02-24 15:35
Could you check if this is a duplicate of #36? Will re-open if not.

**Closed by mattpocock** 2023-02-24 15:35 UTC

**Comment by Jeremias-Nater** [comment] 2023-02-25 16:49
It was indeed a duplicate, the same fix resolved the Issue. With commonJs the imports need to be in this format: `import "@total-typescript/ts-reset/dist/filter-boolean";.

Could you maybe add this to the readme. I copied the import from the readme and therefore assumed it was a Bug which others will probably assume aswell, instead of trying other imports.

Great work @mattpocock btw.
