### ISSUE TITLE
Improve `JSON.parse` and `res.json()` types (more strict)

### ISSUE THREAD

**Issue by GreenTea124** [total-typescript/ts-reset#118] opened 2023-03-21 00:02 UTC
Instead of casting result of `JSON.parse` and `res.json()` to `unknown`, it could be casted to:

```ts
type JSONSerializable =
	| number
	| string
	| boolean
	| null
	| JSONSerializable[]
	| {
			[key: string]: JSONSerializable;
	  };
```

This would be more accurate, and safer since:
```ts
function JSONparse(x: unknown): JSONSerializable {
	return {};
}

const raw = "...";
const a = JSONparse(raw) as { a: string; b: number }; // Ok, compatible
const b = JSONparse(raw) as { a: Date }; // TS Error, `Date` would never be there
```

**Comment by mattpocock** [comment] 2023-03-21 09:00
Duplicate of #10

**Closed as completed by mattpocock** 2023-03-21 09:00 UTC
